version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install poetry
      - poetry install --with docs
    build:
      html:
        - poetry run sphinx-build -M html "docs/source" "$READTHEDOCS_OUTPUT/html"    

sphinx:
  configuration: docs/source/conf.py