version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    # Equivalent to 'pip install .'
    - method: pip
      path: .
    # Equivalent to 'pip install .[docs]'
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py